services:
  netcdf-to-json-backend:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./:/srv/service
    # command: gunicorn --bind=0.0.0.0:5000 --workers=1 --threads=1 --log-level=DEBUG --reload netcdf_to_json_backend.app:app
    env_file: test_environment.env
