exclude = ["venv", "docs/conf.py"]

line-length = 90
target-version = "py312"

[lint]
select = ["E", "F", "UP", "B", "SIM", "I", "W", "C90", "ASYNC", "A", "C4", "PTH", "PERF", "RUF"]
ignore = ["B019"]
